CREATE USER TASK_BD IDENTIFIED BY "Rmi11dp009."
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;
TASK_BD
GRANT CONNECT, RESOURCE TO TASK_BD;
GRANT CREATE SESSION TO TASK_BD;

GRANT CREATE TABLE         TO TASK_BD;
GRANT CREATE VIEW          TO TASK_BD;
GRANT CREATE SEQUENCE      TO TASK_BD;
GRANT CREATE PROCEDURE     TO TASK_BD;
GRANT CREATE TRIGGER       TO TASK_BD;
GRANT UNLIMITED TABLESPACE TO TASK_BD;