CREATE USER CALCULADORA_BD IDENTIFIED BY "Rmi11dp009."
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO CALCULADORA_BD;
GRANT CREATE SESSION TO CALCULADORA_BD;

CREATE USER REPORTES_BD IDENTIFIED BY "Rmi11dp009."
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO REPORTES_BD;
GRANT CREATE SESSION TO REPORTES_BD;